defaults:
  - _self_
  - experiments: weak

training:
  epochs: 300
  validation_examples: 250
  checkpoint_interval: 50
  validation_interval: 50
  batch_size: 1


hydra:
    mode: MULTIRUN
    sweeper:
        params: 
          +training_examples: 250, 500, 750
          +pde_weight: 1., 0.75, 0.5, 0.25
          +lr: 5e-5



