network:
    inputs: 2
    outputs: 3
    layer_size: 60
    nr_layers: 8

optimiser:
    lr: 1e-3
    scheduler: exponential_lr
    iter: 5000
    
hydra:
    mode: MULTIRUN
    sweeper:
        params:
          +n: 5,10,15
          +a_lower: 0.5, 0.7, 0.9
          +a_upper: 1.1, 1.15
          +a: 0.91, 1.05, 1.09
          +pde_coeff: 0.1, 1.0
